name: Update Pack

on:
    schedule:
        - cron: "42 19 * * *" # daily at 19:42 UTC
    workflow_dispatch: {}

concurrency: pack_update

jobs:
    update:
        name: Update
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Checkout Branch
              uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
              with:
                  branch: automation/pack/update

            - name: Fetch Latest pack
              id: latest-pack
              run: |
                  version=$(curl -fsSL https://api.github.com/repos/buildpacks/pack/releases/latest | jq -r .tag_name)
                  version="${version#v}"
                  echo "version=${version}" >> "$GITHUB_OUTPUT"

            - name: Update pack version in tools.json
              id: update-pack
              run: |
                  OLD_VERSION=$(jq -r .pack ./tools.json)
                  NEW_VERSION="${{ steps.latest-pack.outputs.version }}"

                  if [ "${OLD_VERSION}" = "${NEW_VERSION}" ]; then
                    echo "update_needed=false" >> "$GITHUB_OUTPUT"
                    exit 0
                  fi

                  echo "update_needed=true" >> "$GITHUB_OUTPUT"

                  jq --null-input \
                     --sort-keys \
                     --arg pack "${NEW_VERSION}" \
                     '{ pack: $pack }' > ./tools.json

                  IFS='.' read -r o_major o_minor o_patch <<< "${OLD_VERSION}"
                  IFS='.' read -r n_major n_minor n_patch <<< "${NEW_VERSION}"

                  if [[ "$n_major" -gt "$o_major" ]] || [[ "$n_major" -eq "$o_major" && "$n_minor" -gt "$o_minor" ]]; then
                      MESSAGE="feat(deps): update pack CLI from ${OLD_VERSION} to ${NEW_VERSION}"
                  else
                      MESSAGE="fix(deps): bump pack CLI from ${OLD_VERSION} to ${NEW_VERSION}"
                  fi

                  echo "message=${MESSAGE}" >> "$GITHUB_OUTPUT"

            - name: Commit
              id: commit
              if: ${{ steps.update-pack.outputs.update_needed == 'true' }}
              uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
              with:
                  message: ${{ steps.update-pack.outputs.message }}
                  pathspec: "."

            - name: Push Branch
              if: ${{ steps.update-pack.outputs.update_needed == 'true' && steps.commit.outputs.commit_sha != '' }}
              uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
              with:
                  branch: automation/pack/update

            - name: Open Pull Request
              if: ${{ steps.update-pack.outputs.update_needed == 'true' && steps.commit.outputs.commit_sha != '' }}
              uses: paketo-buildpacks/github-config/actions/pull-request/open@main
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: "Update pack to v${{ steps.latest-pack.outputs.version }}"
                  branch: automation/pack/update

    failure:
        name: Alert on Failure
        runs-on: ubuntu-24.04
        needs: [update]
        if: ${{ always() && needs.update.result == 'failure' }}
        steps:
            - name: File Failure Alert Issue
              uses: paketo-buildpacks/github-config/actions/issue/file@main
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  repo: ${{ github.repository }}
                  label: "failure:update-pack"
                  comment_if_exists: true
                  issue_title: "Failure: Update Pack workflow"
                  issue_body: |
                      Update Pack workflow [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
                  comment_body: |
                      Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
